version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: docker_chat_development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d docker_chat_development"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 5000 -b '0.0.0.0'"
    volumes:
      - .:/docker_chat
      - init_volume:/opt/app-initialized
    ports:
      - "5000:5000"
    environment:
      - SERVICE_TYPE=development
      - RAILS_ENV=development
      - DATABASE_URL=postgres://user:password@db/docker_chat_development
    depends_on:
      - db
      - redis

  tests:
    build: .
    environment:
      - SERVICE_TYPE=test
      - RAILS_ENV=test
      - DATABASE_URL=postgres://user:password@db/docker_chat_test
    command: ["./entrypoint.sh", "tests"]
    volumes:
      - .:/docker_chat
      - init_volume:/opt/app-initialized
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  init_volume:
